/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nikola_pavicevic_shoppinglist_JNI */

#ifndef _Included_nikola_pavicevic_shoppinglist_JNI
#define _Included_nikola_pavicevic_shoppinglist_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nikola_pavicevic_shoppinglist_JNI
 * Method:    increment
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_nikola_pavicevic_shoppinglist_JNI_increment
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
